# -*- coding: utf-8 -*-
"""4392_Samuel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWiR1hjFyBOOpr5aBKyXvb0vsYCoHIQp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#1

df = pd.read_csv('/content/Final Dataset - IPL.csv') #reading

df.describe() #understading of the data

df.head()

num_data = df.select_dtypes(include=['int64','float64']).columns #numerical data columns
df.select_dtypes(include=['object']).columns #categorical data columns

df.isnull().sum() #checking for missing values

#2

df.isnull().sum() #checking for missing values

df.dropna()  # dropping missing data

num_data = df.select_dtypes(include=['int64','float64']).columns
df[num_data] = (df[num_data]).fillna(df[num_data].mean()) #just in case, filling missing data with mean


df.duplicated()  #duplicate check

df.drop_duplicates()  #dropping if duplicates present

#3

df[num_data].mean() #Mean

df[num_data].median() #Median

df[num_data].mode()  #Mode

df[num_data].var() #variance

df[num_data].max() - df[num_data].min()  #Range (between max and min)

#4a
#Histogram

import seaborn as sns
sns.histplot(df['first_ings_score'],bins=10,kde=True)
plt.title("First innings score distribution")
plt.xlabel("First innings score")
plt.ylabel("Frequency")

#4a
#scatter plot

sns.scatterplot(x='first_ings_score',y='second_ings_score',hue='venue',data=df)
plt.title('First ings and second ings score comparison across venues')

#4a

sns.boxplot(df['highscore'])
plt.title("Highest scores range")

#4a bar plot

sns.barplot(x='venue',y='second_ings_score',data=df)
plt.xticks(rotation=45)
plt.title("Second innings score by venue")

#4a pie chart
grouping = df.groupby('venue')['first_ings_wkts'].count()
plt.pie(grouping, labels=grouping.index,autopct='%1.1f%%')
plt.title("First innings wickets by venue")

#5

num_data = df.select_dtypes(include=['int64','float64']).columns

correlation_matrix = df[num_data].corr()  #correlation
sns.heatmap(correlation_matrix,annot=True,fmt=".2f") #correlation visualization


sales_profit_correlation = df[''].corr(df['Profit'])


df['second_ings_score'].corr(df['first_ings_score']) #sample correlation case
df['first_ings_score'].corr(df['top_scorer']) #sample correlation case

#6 check for outliers

num_data = df.select_dtypes(include=['int64','float64']).columns

for i in num_data:
  sns.boxplot(df[i])
  plt.show()

#6 outlier handling - IQR method used and np.where to check where
#There is an alternate way of using threshold (such as thres = 2 and np.where thresh<2)

def handling(j,columns):
  for j in columns:
    Q1=df[j].percentile(0.25)
    Q3=df[j].percentile(0.75)
    IQR=Q3-Q1
    lower_range=IQR-1.5*Q1
    upper_range =IQR+1.5*Q3
    med = df[j].median()
    df[j] = np.where((df[j] < lower_range) | (df[j] > upper_range), med, df[j])
    return df

# 7

df

#7


individual_topscorer_performance = df.groupby('top_scorer')['highscore'].count()

teamwise_performance = df['match_winner'].value_counts()  #team wise

venue_performance_firstingsbyteams = df.groupby('venue')['first_ings_score'].sum()

venue_performance_secondingsbyteams = df.groupby('venue')['second_ings_score'].sum()

player_standout_performance = df['player_of_the_match'].value_counts() #individual wise

venue_effect = df.groupby('venue')['match_winner'].value_counts().unstack()

# from winner_by_venue it is clear that venue does affect the teams ability to win, especially home teams

#8

df['player_of_the_match'].value_counts()

# Kuldeep yadav has the most player of the match awards

#impact of best bolwers on team's success is as follows

grouped_data = df.groupby(['best_bowling', 'match_winner'])

count_data = grouped_data['match_winner'].count().unstack()

count_data.sort_values(ascending=False).index[0]

#impact of top scorer on team's success is as follows

grouping_data = df.groupby(['top_scorer', 'match_winner'])

countof_data = grouped_data['match_winner'].count().unstack()

countof_data.sort_values(ascending=False)

#9

# EFFECT OF VENUE:

# 1. Venue has a direct impact on the wickets lost by teams. Be it first innings and second innings. The pie chart below is a depiction of how it affects both first innings wickets.

# 2. Venue has a direct impact on the first and second innings scores posted by teams as well.

grouping = df.groupby('venue')['first_ings_wkts'].count()
plt.pie(grouping, labels=grouping.index,autopct='%1.1f%%')
plt.title("First innings wickets by venue")

#
#
#INDIVIDUAL BRILLIANCE:

#Kuldeep Yadav leads the way with most player of the match performances.

#Interesting Jos Buttler's player of the match performances has always contributed to the team's success as his team has gone on to win them.

# TOP SCORES:

#Seem to fall commonly in the range of 50-80 without

# No major shocking outliers interestingly and no standout top score

























































































































